### ISSUE TITLE
quest.zip

### ISSUE THREAD

**Issue by c000127** [TeyvatL/GrasscutterTool-2.8.5#3]
deflate + aes256 ，真的会有所谓的解密技术吗？

**Comment by Sycamore0** [comment]
我没有给这个压缩文件出题。
如果想破解的话只能用hashcat慢慢弄了(虽然这有些困难,lol)

**Comment by Sycamore0** [comment]
目前我只使用base64加密了密码原文，所以我不能给题目。
或许可以用protobuf+base64+xor加密一下再出题。 :Think:

**Comment by Sycamore0** [comment]
目前我只使用base64加密了密码原文，所以我不能给题目。
或许可以用protobuf+base64+xor加密一下再出题。 :Think:
