### ISSUE TITLE
耍无赖

### ISSUE THREAD

**Issue by Kawaa-qwq** [TeyvatL/GrasscutterTool-2.8.5#5]
所以我这算成功还是不成功:(

**Comment by qianyu1431** [comment]
同问同问，kawaa牛逼！10分钟解出来了！
Ask the same question, kawaa! 10 minutes to solve it!

**Comment by MLChinoo** [comment]
牛逼

**Comment by qianyu1431** [comment]
![image](https://user-images.githubusercontent.com/74231782/183296531-c7b42768-8ac9-4bce-aa49-40391ebf5e5d.png)
顺便说一句，谢谢你的id~
By the way, thank you for id~

**Comment by Sycamore0** [comment]
寄，还好没放其他的额外res

**Comment by qianyu1431** [comment]
> 寄，还好没放其他的额外res

你耍无赖，kawaa解出来了好不好

**Comment by Sycamore0** [comment]
你们可以在q群公布，但别在这

**Comment by qianyu1431** [comment]
不 我们不会公布

**Comment by qianyu1431** [comment]
在公众普及开始 我们不会做出头鸟

**Comment by Sycamore0** [comment]
![-39c93b7d221f6649](https://user-images.githubusercontent.com/64587684/183296903-87594296-e02f-449e-accb-8e9d3dde8ba8.jpg)

**Comment by qianyu1431** [comment]
请问一下 你是天理的服主吗？

**Comment by Sycamore0** [comment]
不，我不是，我只是一个弄本地端的萌新罢了

**Comment by qianyu1431** [comment]
no 我就是看到你dc发的我才找到这里来的

**Comment by Sycamore0** [comment]
在哪？
截图给我看看

**Comment by Sycamore0** [comment]
不会是罗刹吧

**Comment by qianyu1431** [comment]
![image](https://user-images.githubusercontent.com/74231782/183297125-f4583df0-bc9c-4d62-8ae3-9af68cf3085c.png)

**Comment by qianyu1431** [comment]
这不是你本人么

**Comment by Sycamore0** [comment]
额，我可以说我看不见你的消息吗

**Comment by qianyu1431** [comment]
庫卡🅺🅾🅺🅰

**Comment by Sycamore0** [comment]
不是我，我叫WindSeedClientNotify

**Comment by Sycamore0** [comment]
> 不是我，我叫WindSeedClientNotify

在dc里

**Comment by qianyu1431** [comment]
你看一下小白提问区

**Comment by qianyu1431** [comment]
hhh

**Comment by Sycamore0** [comment]
先随便放个截图在readme罢

**Comment by Kawaa-qwq** [comment]
可爱捏
